name: gaussian_splatting
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - faiss=1.7.4
  - faiss-cpu=1.7.4
  - joblib=1.5.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.30
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.5.2
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.9.23
  - python_abi=3.9
  - readline=8.3
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - setuptools=78.1.1
  - sqlite=3.50.2
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - black==25.1.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.1.8
      - contourpy==1.3.0
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - diff-gaussian-rasterization==0.0.0
      - exceptiongroup==1.3.0
      - faiss-gpu==1.7.2
      - fastrlock==0.8.3
      - filelock==3.13.1
      - flake8==7.3.0
      - fonttools==4.59.2
      - fsspec==2024.6.1
      - fused-ssim==0.0.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.0
      - idna==3.10
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lightglue==0.0
      - llvmlite==0.43.0
      - lpips==0.1.4
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mccabe==0.7.0
      - mpmath==1.3.0
      - mypy==1.18.1
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pathspec==0.12.1
      - pillow==11.0.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - plyfile==1.1.2
      - psutil==7.0.0
      - pyceres==2.5
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.2.4
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.5
      - safetensors==0.6.2
      - simple-knn==0.0.0
      - six==1.17.0
      - sympy==1.13.1
      - timm==1.0.20
      - tomli==2.2.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - urllib3==2.5.0
      - zipp==3.23.0
prefix: /home/meic-jbc/anaconda3/envs/gaussian_splatting
